displayName=Better Party Def
author=Heisty
description=A Better Hub Party Panel Defence Tracker, enjoy! 
tags=defence,defense,drain,party,hub,boss,special
plugins=net.betterpartydefence.BetterPartyDefencePlugin
build=standard
version=1.1
